### ISSUE TITLE
List images created by @Ol' Bootsie

### ISSUE THREAD

**Issue by losmykie** [jlyons210/discord-bot-ol-bootsie#77]
With the addition of DALL·E 2 to Ol'Bootsie, it would be helpful to have a command to show all images a user created or images that were created in a channel by all users. : 

**Example**
```
@Ol' Bootsie list the last 10 images created by @og_grumple 
@Ol' Bootsie list the last 10 images created
```

**Comment by jlyons210** [comment]
I thought about this one for a long time.

Since the bot is stateless (doesn't store anything), there is no history to pull from. Since one bot instance can support multiple servers and channels, and the requestor might not have access to other places that the one user generated images within, privacy needs to be maintained. I'd have to restrict it to images generated in the channel the request was being made within, which essentially becomes a shortcut for scrolling up.

I appreciate the suggestion though, keep em coming 😁
